### ISSUE TITLE
Overzealous use of debug.log

### ISSUE THREAD

**Issue by harbingerofme** [Vale-X/ModdersItems#2]
https://github.com/Vale-X/ModdersItems/blob/5b1b66bfb1a9ba70e650d393064fa29a00d7574f/Assets/ModdersItems/Scripts/Tokens.cs#L25

For every token, not only is it logged, but it's also using the unity engine logging which means you don't even get the log filter advantage BepInEx provides.
These should be trace level logs

**Comment by Vale-X** [comment]
Added a custom logger and hopefully used logging more appropriately. Thanks for letting me know about this!

Note that not each token was logged, but each TokenBase script that's initialized was (For example, only a single log for `ValeTokens`). Regardless, I've removed this.
