### ISSUE TITLE
Packages copied into gitrepo

### ISSUE THREAD

**Issue by harbingerofme** [Vale-X/ModdersItems#3]
These should be acquired through a setup process, roght now you are redistributing all of them

**Comment by harbingerofme** [comment]
In particular, this is bad because a lot of these have MIT or LGPL licenses and these licenses are not included.

**Comment by Vale-X** [comment]
https://github.com/Vale-X/ModdersItems/commit/106a68431ad6aa2601e6779a9e6583a627217e0f 

Temporary solution as mentioned by hargbingerofme on the discord. All of the license files relating to the packages with licenses have been added.
